import type { AppData, Career } from '@/types';

const sampleCareer: Career = {
  id: 'c1',
  title: 'Software Engineer',
  slug: 'software-engineer',
  department: 'Software Engineering',
  location: 'Sri Lanka / Remote',
  employmentType: 'Full Time',
  experienceLevel: 'Junior / Mid Level',
  shortDescription: 'Join our engineering team and build modern digital solutions.',
  description: 'Build modern digital solutions with the Evox engineering team.',
  responsibilities: ['Develop modern web applications'],
  requirements: ['Strong programming fundamentals'],
  skills: ['React', '.NET', 'PostgreSQL'],
  preferredSkills: [],
  benefits: ['Professional development'],
  salary: '',
  applicationMethod: 'email',
  applicationEmail: 'info@evoxtech.com',
  applicationUrl: '',
  applicationInstructions: '',
  postedDate: '2026-09-29',
  applicationDeadline: '2026-10-30',
  status: 'Published',
  featured: true,
};

export const defaultData: AppData = {
  projects: [
    {
      id: 'p1',
      title: 'Smart Retail POS System',
      description: 'A comprehensive point-of-sale system with inventory management, real-time analytics, and multi-store support.',
      image: '',
      technologies: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
      industry: 'Retail',
      status: 'completed',
      url: 'https://example.com/pos',
      featured: true,
      displayOrder: 1,
    },
  ],
  directors: [
    {
      id: 'd1',
      name: 'Roshan Perera',
      designation: 'Managing Director & CEO',
      image: '',
      bio: 'Roshan founded Evox Technology in 2015.',
      displayOrder: 1,
      active: true,
    },
  ],
  careers: [sampleCareer],
  company: {
    name: 'Evox Technology (Pvt) Ltd',
    description: 'Premier software development company.',
    about: 'Founded in 2015.',
    mission: 'To empower businesses with transformative technology.',
    vision: 'To be the most trusted technology partner.',
    tagline: 'Engineering Tomorrow\'s Solutions, Today',
    foundedYear: '2025',
    email: 'info@evoxtech.com',
    phone: '+94 11 234 5678',
    whatsapp: '+94 77 123 4567',
    website: 'https://www.evoxtech.com',
    registration: 'PV 00234567',
  },
  address: {
    line1: 'No. 142, Galle Road',
    line2: 'Colombo 03',
    city: 'Colombo',
    province: 'Western Province',
    country: 'Sri Lanka',
    postalCode: '00300',
    mapsUrl: '',
  },
  branding: {
    mainLogo: '/images/company/logo.svg',
    footerLogo: '/images/company/logo-light.svg',
    favicon: '/images/company/favicon.svg',
    darkLogo: '/images/company/logo-dark.svg',
    lightLogo: '/images/company/logo-light.svg',
  },
  social: {
    email: 'info@evoxtech.com',
    phone: '+94 11 234 5678',
    whatsapp: '+94 77 123 4567',
    linkedin: 'https://www.linkedin.com/company/evoxtech',
    facebook: 'https://www.facebook.com/evoxtech',
    instagram: 'https://www.instagram.com/evoxtech',
    youtube: 'https://www.youtube.com/@evoxtech',
    github: 'https://github.com/evoxtech',
    other: '',
    enabled: {
      linkedin: true,
      facebook: true,
      instagram: true,
      youtube: true,
      github: true,
      other: false,
    },
  },
  settings: {
    title: 'Evox Technology | Software Development & Digital Solutions',
    metaDescription: 'Premier software development company.',
    footerCopyright: 'Evox Technology (Pvt) Ltd. All rights reserved.',
  },
};
